name: windmillcode_flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter continauation of Jesway/flutter_translate library to be maintained.
version: 5.0.2
homepage: https://windmillcode.com
repository: https://github.com/WindMillCode/flutter_translate
topics:
  - localization
  - i18n
  - translation
  - internationalization
  - flutter

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0-0 <=0.19.0'
  shared_preferences: '>=2.2.2 <3.0.0'
  path: '>=1.8.0 <2.0.0'
  collection: '>=1.17.0 <2.0.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=2.0.2 <4.0.0'
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
